// don't fix, stil in research phase
interface Template {
    type: 'web' | 'app' | 'desktop' | 'backend' | 'fullstack' | 'deployment' | 'library'
    name: string
    tools: string[]
    vlist: string[]
    additionalTools: string[]
    description: string
}

const templates: Template[] = [
    // --- WEB STACKS ---
    {
        type: 'web',
        name: 'next-enterprise',
        tools: ['nextjs', 'typescript', 'trpc'],
        vlist: ['15.x', '14.x'],
        additionalTools: [
            'tailwind',
            'shadcn',
            'drizzle-orm',
            'lucide',
            'next-auth',
            'react-hook-form',
            'zod',
            'zustand',
            'framer-motion',
            'react-query',
            'eslint',
            'prettier',
            'husky',
            'lint-staged',
            'jest',
            'testing-library',
            'playwright',
            'storybook',
            'turbopack',
            'vercel',
        ],
        description: 'Full-stack RSC architecture with type-safe API.',
    },
    {
        type: 'web',
        name: 'vite-spa',
        tools: ['vite', 'react', 'typescript'],
        vlist: ['5.x', '4.x'],
        additionalTools: [
            'tanstack-query',
            'zustand',
            'biome',
            'react-router-dom',
            'styled-components',
            'chakra-ui',
            'mantine',
            'formik',
            'yup',
            'axios',
            'swr',
            'jotai',
            'valtio',
            'cypress',
            'vitest',
            'msw',
            'rollup',
            'esbuild',
        ],
        description: 'Ultra-fast Single Page Application with modern linting.',
    },
    {
        type: 'web',
        name: 'remix-standard',
        tools: ['remix', 'react'],
        vlist: ['2.x', '1.x'],
        additionalTools: [
            'prisma',
            'radix-ui',
            'zod',
            'tailwind',
            'postcss',
            'autoprefixer',
            'remix-auth',
            'remix-utils',
            'conform',
            'sqlite',
            'postgresql',
            'redis',
            'session-storage',
            'cookie-parser',
            'helmet',
            'compression',
        ],
        description: 'Web-standard focused full-stack framework.',
    },
    {
        type: 'web',
        name: 'nuxt-fullstack',
        tools: ['nuxt', 'vue', 'typescript'],
        vlist: ['3.x'],
        additionalTools: [
            'pinia',
            'nitro',
            'nuxt-ui',
            'vueuse',
            'vue-router',
            'vuetify',
            'quasar',
            'primevue',
            'headlessui-vue',
            'vue-test-utils',
            'vitest',
            'cypress',
            'nuxt-auth',
            'nuxt-i18n',
            'nuxt-image',
            'nuxt-content',
        ],
        description: 'Vue-based full-stack framework with server-side rendering.',
    },
    {
        type: 'web',
        name: 'svelte-kit',
        tools: ['sveltekit', 'svelte', 'typescript'],
        vlist: ['2.x', '1.x'],
        additionalTools: [
            'tailwind',
            'playwright',
            'vitest',
            'svelte-check',
            'carbon-components-svelte',
            'skeleton-ui',
            'threlte',
            'svelte-forms-lib',
            'yup',
            'lucia-auth',
            'prisma',
            'drizzle',
            'mdsvex',
            'svelte-spa-router',
        ],
        description: 'Modern web framework with minimal runtime overhead.',
    },

    // --- MOBILE STACKS ---
    {
        type: 'app',
        name: 'rn-expo',
        tools: ['react-native', 'expo', 'typescript'],
        vlist: ['0.74.x', '0.73.x'],
        additionalTools: [
            'tamagui',
            'expo-router',
            'reanimated',
            'react-navigation',
            'native-base',
            'react-native-elements',
            'react-native-paper',
            'expo-notifications',
            'expo-location',
            'expo-camera',
            'expo-auth-session',
            'async-storage',
            'react-native-mmkv',
            'react-query',
            'zustand',
            'detox',
            'flipper',
            'reactotron',
            'sentry',
            'firebase',
            'expo-updates',
        ],
        description: 'Native cross-platform app with optimized routing.',
    },
    {
        type: 'app',
        name: 'flutter-gs',
        tools: ['flutter', 'dart'],
        vlist: ['3.x'],
        additionalTools: [
            'riverpod',
            'go_router',
            'freezed',
            'json_annotation',
            'dio',
            'hive',
            'sqflite',
            'shared_preferences',
            'provider',
            'bloc',
            'get',
            'firebase_core',
            'firebase_auth',
            'cloud_firestore',
            'flutter_test',
            'integration_test',
            'mocktail',
            'golden_toolkit',
            'flutter_launcher_icons',
            'flutter_native_splash',
        ],
        description: 'Pixel-perfect UI with robust state management.',
    },
    {
        type: 'app',
        name: 'capacitor-ionic',
        tools: ['capacitor', 'ionic', 'typescript'],
        vlist: ['5.x', '4.x'],
        additionalTools: [
            'angular',
            'rxjs',
            'ionic-native',
            'ionic-storage',
            'ionic-react',
            'ionic-vue',
            'capacitor-community',
            'cordova-plugins',
            'pouchdb',
            'firebase',
            'auth0',
            'stripe',
            'admob',
            'onesignal',
            'camera',
            'geolocation',
            'device',
            'network',
            'statusbar',
            'splashscreen',
        ],
        description: 'Hybrid mobile apps using web technologies.',
    },

    // --- DESKTOP & HYBRID ---
    {
        type: 'desktop',
        name: 'tauri-react',
        tools: ['tauri', 'rust', 'react'],
        vlist: ['1.x'],
        additionalTools: [
            'vite',
            'shadcn',
            'tailwind',
            'tauri-plugin-store',
            'tauri-plugin-fs',
            'tauri-plugin-shell',
            'tauri-plugin-dialog',
            'tauri-plugin-notification',
            'serde',
            'tokio',
            'reqwest',
            'sqlx',
            'sea-orm',
            'wasm-bindgen',
            'web-sys',
        ],
        description: 'Lightweight desktop app using Rust core and React UI.',
    },
    {
        type: 'desktop',
        name: 'electron-forge',
        tools: ['electron', 'typescript', 'webpack'],
        vlist: ['28.x', '27.x'],
        additionalTools: [
            'react',
            'electron-updater',
            'node-pty',
            'electron-builder',
            'electron-store',
            'electron-log',
            'electron-debug',
            'electron-reload',
            'electron-devtools-installer',
            'menubar',
            'auto-launch',
            'node-notifier',
            'keytar',
            'systray',
        ],
        description: 'Cross-platform desktop apps with Node.js runtime.',
    },

    // --- BACKEND & API ---
    {
        type: 'backend',
        name: 'fastify-enterprise',
        tools: ['fastify', 'typescript', 'nodejs'],
        vlist: ['4.x'],
        additionalTools: [
            'prisma',
            'zod',
            'swagger',
            'jwt',
            'fastify-cors',
            'fastify-helmet',
            'fastify-rate-limit',
            'fastify-multipart',
            'fastify-static',
            'fastify-compress',
            'pino',
            'winston',
            'redis',
            'bull',
            'nodemailer',
            'bcrypt',
            'argon2',
            'dotenv',
            'joi',
            'ajv',
        ],
        description: 'High-performance Node.js API with validation.',
    },
    {
        type: 'backend',
        name: 'nestjs-graphql',
        tools: ['nestjs', 'graphql', 'typescript'],
        vlist: ['10.x', '9.x'],
        additionalTools: [
            'apollo',
            'typeorm',
            'passport',
            'bull',
            'class-validator',
            'class-transformer',
            'config',
            'jwt',
            'bcrypt',
            'helmet',
            'compression',
            'redis',
            'mongodb',
            'postgresql',
            'mysql',
            'sqlite',
            'prisma',
            'mikro-orm',
            'sequelize',
            'dataloader',
            'graphql-subscriptions',
        ],
        description: 'Scalable server-side applications with GraphQL.',
    },
    {
        type: 'backend',
        name: 'express-rest',
        tools: ['express', 'typescript', 'nodejs'],
        vlist: ['4.x'],
        additionalTools: [
            'mongoose',
            'joi',
            'helmet',
            'cors',
            'express-rate-limit',
            'express-validator',
            'multer',
            'morgan',
            'compression',
            'cookie-parser',
            'express-session',
            'connect-redis',
            'passport',
            'jsonwebtoken',
            'bcryptjs',
            'nodemailer',
            'agenda',
            'winston',
            'dotenv',
        ],
        description: 'Traditional REST API with MongoDB integration.',
    },

    // --- FULLSTACK & DEPLOYMENT ---
    {
        type: 'fullstack',
        name: 't3-stack',
        tools: ['nextjs', 'trpc', 'typescript'],
        vlist: ['15.x', '14.x'],
        additionalTools: [
            'prisma',
            'nextauth',
            'tailwind',
            'zod',
            'react-hook-form',
            'tanstack-query',
            'zustand',
            'uploadthing',
            'vercel',
            'planetscale',
            'railway',
            'supabase',
            'clerk',
            'stripe',
            'resend',
            'pusher',
            'lemon-squeezy',
        ],
        description: 'Type-safe full-stack with modern tooling.',
    },
    {
        type: 'deployment',
        name: 'docker-compose',
        tools: ['docker', 'nginx', 'postgresql'],
        vlist: ['24.x', '23.x'],
        additionalTools: [
            'redis',
            'prometheus',
            'grafana',
            'elasticsearch',
            'kibana',
            'logstash',
            'traefik',
            'caddy',
            'consul',
            'vault',
            'jenkins',
            'gitlab-ci',
            'github-actions',
            'terraform',
            'ansible',
            'kubernetes',
            'helm',
            'istio',
        ],
        description: 'Containerized application stack with monitoring.',
    },

    // --- LIBRARIES & PACKAGES ---
    {
        type: 'library',
        name: 'npm-package',
        tools: ['typescript', 'rollup', 'vitest'],
        vlist: ['5.x'],
        additionalTools: [
            'changeset',
            'eslint',
            'prettier',
            'husky',
            'lint-staged',
            'semantic-release',
            'release-it',
            'np',
            'size-limit',
            'bundlesize',
            'babel',
            'swc',
            'esbuild',
            'tsup',
            'unbuild',
            'publint',
            'arethetypeswrong',
        ],
        description: 'Modern NPM package with automated publishing.',
    },
    {
        type: 'library',
        name: 'react-component',
        tools: ['react', 'typescript', 'storybook'],
        vlist: ['18.x'],
        additionalTools: [
            'rollup',
            'testing-library',
            'chromatic',
            'jest',
            'react-hooks-testing-library',
            'enzyme',
            'styled-components',
            'emotion',
            'framer-motion',
            'react-spring',
            'react-transition-group',
            'prop-types',
            'clsx',
            'classnames',
            'react-use',
        ],
        description: 'Reusable React components with visual testing.',
    },
]

export { templates }
